<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'variable.aes_key_path' => 'ec168c0710152c95610fbbd1f01dc7ec16141d81',
  'variable.aes_key_storage_method' => 'ef6d67e8f6269aaf606289b9221ed03ccf1f15ef',
  'variable.configuration_config_path' => '1c4893124e45f0883bcab14578532b072e02c315',
  'variable.configuration_exclude_configurations' => 'df1d52339fcfc543a60ccc18be690f64bbc4450c',
  'variable.configuration_remote_server' => '79172eb30d86cdc0f70ba313d46f0f1728bc8bcb',
  'variable.xautoload_cache_prefix' => 'd827d88803bc316ebc1d0b9c3984ef7c150060ea',
);


// The following modules are required to run the configurations of this file.

$modules = array(
);
